language: objective-c
sudo: false
os: osx
osx_image: beta-xcode6.3

script:
- xcodebuild -showsdks
- instruments -s devices
- xctool -workspace bither-ios.xcworkspace -scheme bither-ios -sdk iphonesimulator8.3 ONLY_ACTIVE_ARCH=NO
